FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /grapheditor

# copy project files and folders to the current working directory (i.e. 'grapheditor' folder)
COPY . .

EXPOSE 8080
CMD [ "http-server" ]